// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using takeup.Services.VoteSystem.Domain.Database.DbContexts;

#nullable disable

namespace takeup.Services.VoteSystem.Domain.Migrations
{
    [DbContext(typeof(VoteSystemDbContext))]
    [Migration("20260208065801_Add_config")]
    partial class Add_config
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("takeup.Services.VoteSystem.Domain.Database.Entities.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AnswerAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnswerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Configs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerAt = 0L,
                            AnswerId = 0
                        });
                });

            modelBuilder.Entity("takeup.Services.VoteSystem.Domain.Database.Entities.Data", b =>
                {
                    b.Property<int>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DataId");

                    b.ToTable("Data");

                    b.HasDiscriminator().HasValue("Data");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("takeup.Services.VoteSystem.Domain.Database.Entities.Snapshot", b =>
                {
                    b.Property<long>("DateTimeHour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("DateTimeHour");

                    b.ToTable("Snapshots");
                });

            modelBuilder.Entity("takeup.Services.VoteSystem.Domain.Database.Entities.Topic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TopicId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("takeup.Services.VoteSystem.Domain.Database.Entities.Vote", b =>
                {
                    b.Property<Guid>("IPHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("TopicId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IPHash", "TopicId", "DataId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("takeup.Services.VoteSystem.Domain.Database.Entities.PendingData", b =>
                {
                    b.HasBaseType("takeup.Services.VoteSystem.Domain.Database.Entities.Data");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("PendingData");
                });
#pragma warning restore 612, 618
        }
    }
}
